title: Pengfei Yu
email: life4pf@gmail.com
description: Researcher building intelligence.
baseurl: ""
url: "https://perfec-yu.github.io"
repository: Perfec-Yu/Perfec-Yu.github.io
masthead_title: 于
# logo: /assets/images/logo.png
# teaser:

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
  - scope:
      path: ""
    values:
      classes: wide

enable_copy_code_button: true
atom_feed:
  hide: true

twitter:
  username: PengfeiYu7
social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://x.com/PengfeiYu7"
    - "https://www.linkedin.com/in/pengfei-yu-89a940256/"
github:
  username: Perfec-Yu


author:
  name     : "Pengfei Yu"
  avatar   : "/assets/images/teaser_profile.png"
  bio      : |
    life4pf AT gmail DOT com
    
    Working on Agentic RL for LLMs.

    <img class="inline-icon" src="/assets/icons/uiuc_square.svg" alt="University of Illinois Urbana–Champaign"> PhD from University of Illinois Urbana–Champaign in Computer Science.

    <img class="inline-icon" src="/assets/icons/thu.svg" alt="Tsinghua University"> Bachelor's Degree from Tsinghua University in Electronic Engineering and Mathematics.

  location : "CA, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Perfec-Yu"
    - label: Google-Scholar
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=bFbykBYAAAAJ&hl=en"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pengfei-yu-89a940256/"
    - label: X
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/PengfeiYu7"
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Build settings
# theme: minima
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: dirt
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-paginate-v2